schoolmate/config/routes.rb
Schoolmate::Application.routes.draw do
  root :to => 'diary#index'

  resources :users
  resources :sessions
  resources :notifications
  resources :profiles
  resources :finances
  resources :options do
    collection do
      get  :index
      get  :about
      get  :feedback
      post :send_feedback
    end
  end
  resources :years do
    resources :terms do
      member do 
        get 'assign_subject'
        post 'add_subject'
      end
    end
  end
  resources :exams
  resources :exam_watchers
  resources :subjects
  resources :marks

  match "login"     => "sessions#new", :via => :get
  match "logout"    => "sessions#destroy", :via => :get
  match "signup"    => "users#new", :via => :get
  match 'diary'     => 'diary#index'
  match 'diary_add' => 'diary#add'
  match 'home'      => 'home#index', :via => :get
  match 'study'     => 'study#index', :via => :get
  



  

end

schoolmate/app/models/finance.rb
class Finance < ActiveRecord::Base
    attr_accessible :value, :user_id
    validates :value, :presence => true

    belongs_to :user

end

schoolmate/app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_filter :require_authentication
  layout "mobile"
  
  def index
    @finances = current_user.finances    
  end

  def edit
    @finance = Finance.find(params[:id])
  end

  def destroy
    finance = Finance.find(params[:id])
    if finance.user_id != current_user.id
        flash[:error] = t('finance.not_belong')
        redirect_to finances_path
    end
    if finance.delete
        flash[:info] = t('finance.deleted')
    else
        flash[:error] = t('finance.delete_error')
    end
    redirect_to finances_path 
  end

  def create
    finance = Finance.new(value:params[:value], user_id:current_user.id)
    if finance.save
      flash[:info] = t('finance.created')
      redirect_to finances_path  
    else
      flash[:error] = t('finance.create_error')
      redirect_to new_finance_path
    end    
  end

  def new
    @finance = Finance.new
  end

end

schoolmate/app/helpers/finances_helper.rb
module FinancesHelper

    def date_with_month(finance)
        localize finance.created_at, :format => '%B %d, %Y'
    end    

end

schoolmate/app/views/finances/edit.html.haml
= content_for :title do
  = @finance.created_at.strftime("%d-%m-%Y")
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => finances_path}
    Финансы  
  = link_to("Удалить", finance_path(@finance), :method => :delete, :class => "ui-btn-right", :data => {icon:"delete"})
  -#%a.ui-btn-right{"data-icon" => "delete", :href => new_finance_path} Удалить
%div
  %h3
    = date_with_month(@finance)
  %h4
    Сумма:
    = @finance.value
    рублей
  

schoolmate/app/views/finances/index.html.haml
= content_for :title do
  Финансы
= content_for :buttons do
  %a{"data-icon" => "home", :href => diary_path}
    События  
  %a.ui-btn-right{"data-icon" => "plus", :href => new_finance_path} Добавить
%div
  %ul{"data-role" => "listview", "data-filter" => "true"}
    -@finances.each do |finance|
      %li
        = link_to edit_finance_path(finance) do
          = date_with_month(finance)            
          %span.ui-li-count
            = finance.value

schoolmate/app/views/finances/new.html.haml
= content_for :title do
  Внесение денег
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => finances_path}
    Финансы  
%div
  %h3
    Внесение наличных денег за оплату питания ребенка от 
    = Time.zone.now.strftime("%d-%m-%Y")
  = form_for @finance do |f|
    %div
      = label_tag(:value, "Сумма:")
      = text_field_tag(:value, @finance.value, :placeholder => "сумма" )
      = f.submit "Сохранить" 