schoolmate/config/routes.rb
Schoolmate::Application.routes.draw do
  root :to => 'diary#index'

  resources :users
  resources :sessions
  resources :notifications
  resources :profiles
  resources :finances
  resources :options do
    collection do
      get  :index
      get  :about
      get  :feedback
      post :send_feedback
    end
  end
  resources :years do
    resources :terms do
      member do 
        get 'assign_subject'
        post 'add_subject'
      end
    end
  end
  resources :exams
  resources :exam_watchers
  resources :subjects
  resources :marks

  match "login"     => "sessions#new", :via => :get
  match "logout"    => "sessions#destroy", :via => :get
  match "signup"    => "users#new", :via => :get
  match 'diary'     => 'diary#index'
  match 'diary_add' => 'diary#add'
  match 'home'      => 'home#index', :via => :get
  match 'study'     => 'study#index', :via => :get
  



  

end

schoolmate/app/models/subject.rb
class Subject < ActiveRecord::Base

    belongs_to :user
    has_and_belongs_to_many :terms

    attr_accessible :name, :user_id
    validates :name, :presence => true

end

schoolmate/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :require_authentication
  layout "mobile"
  
  def index
    @subjects = current_user.subjects    
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def destroy
    subject = Subject.find(params[:id])
    if subject.user_id != current_user.id
        flash[:error] = t('subject.not_belong')
        redirect_to subjects_path
    end
    if subject.delete
        flash[:info] = t('subject.deleted')
    else
        flash[:error] = t('subject.delete_error')
    end
    redirect_to subjects_path 
  end

  def create
    subject = Subject.new(name:params[:name], user_id:current_user.id)
    if subject.save
      flash[:info] = t('subject.created')
      redirect_to subjects_path  
    else
      flash[:error] = t('subject.create_error')
      redirect_to new_subject_path
    end    
  end

  def new
    @subject = Subject.new
  end

  def update
    subject = Subject.find(params[:id])
    if subject.user_id != current_user.id
        flash[:error] = t('subject.not_belong')
        redirect_to subjects_path
    end
    subject.name = params[:name]
    if subject.save
        flash[:info] = t('subject.updated')
    else
        flash[:error] = t('subject.update_error')
    end    
    redirect_to subjects_path 
  end

end

schoolmate/app/views/subjects/_form.html.haml
= form_for @subject do |f|
  %div
    = label_tag(:name, "Название:")
    = text_field_tag(:name, @subject.name, :placeholder => "название" )
    = f.submit "Сохранить" 

schoolmate/app/views/subjects/edit.html.haml
= content_for :title do
  = @subject.name
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => subjects_path}
    Предметы  
  = link_to("Удалить", subject_path(@subject), :method => :delete, :class => "ui-btn-right", :data => {icon:"delete"})
%div
  = render 'form'
  

schoolmate/app/views/subjects/index.html.haml
= content_for :title do
  Предметы
= content_for :buttons do
  %a{"data-icon" => "home", :href => diary_path}
    События  
  %a.ui-btn-right{"data-icon" => "plus", :href => new_subject_path} Добавить
%div
  %ul{"data-role" => "listview", "data-filter" => "true" }
    -@subjects.each do |subject|
      %li
        = link_to edit_subject_path(subject) do
          = subject.name 

schoolmate/app/views/subjects/new.html.haml
= content_for :title do
  Новый предмет
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => subjects_path}
    Предметы  
%div
  = render 'form'