schoolmate/config/routes.rb
Schoolmate::Application.routes.draw do
  root :to => 'diary#index'

  resources :users
  resources :sessions
  resources :notifications
  resources :profiles
  resources :finances
  resources :options do
    collection do
      get  :index
      get  :about
      get  :feedback
      post :send_feedback
    end
  end
  resources :years do
    resources :terms do
      member do 
        get 'assign_subject'
        post 'add_subject'
      end
    end
  end
  resources :exams
  resources :exam_watchers
  resources :subjects
  resources :marks

  match "login"     => "sessions#new", :via => :get
  match "logout"    => "sessions#destroy", :via => :get
  match "signup"    => "users#new", :via => :get
  match 'diary'     => 'diary#index'
  match 'diary_add' => 'diary#add'
  match 'home'      => 'home#index', :via => :get
  match 'study'     => 'study#index', :via => :get
  



  

end

schoolmate/app/models/year.rb
class Year < ActiveRecord::Base

    belongs_to :user
    has_many :terms

    attr_accessible :code, :user_id
    validates :code, :presence => true
    validates :code, :numericality => { :only_integer => true }

end

schoolmate/app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_filter :require_authentication
  layout "mobile"
  
  def edit
    @year = Year.find(params[:id])
  end

  def destroy
    year = Year.find(params[:id])
    if year.user_id != current_user.id
        flash[:error] = t('year.not_belong')
        redirect_to study_path
    end
    if year.delete
        flash[:info] = t('year.deleted')
    else
        flash[:error] = t('year.delete_error')
    end
    redirect_to study_path 
  end

  def create
    year = Year.new(code:params[:code], user_id:current_user.id)
    if year.save
      flash[:info] = t('year.created')
      redirect_to study_path  
    else
      flash[:error] = t('year.create_error')
      redirect_to new_year_path
    end    
  end

  def new
    @year = Year.new
  end

  def update
    year = Year.find(params[:id])
    if year.user_id != current_user.id
        flash[:error] = t('year.not_belong')
        redirect_to study_path
    end
    year.code = params[:code]
    if year.save
        flash[:info] = t('year.updated')
    else
        flash[:error] = t('year.update_error')
    end    
    redirect_to study_path 
  end

end

schoolmate/app/views/years/_form.html.haml
= form_for @year do |f|
  %div
    = label_tag(:code, "Название:")
    = text_field_tag(:code, @year.code, :placeholder => "название" )
    = f.submit "Сохранить" 

schoolmate/app/views/years/edit.html.haml
= content_for :title do
  = @year.code
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => study_path}
    Учеба  
  = link_to("Удалить", year_path(@year), :method => :delete, :class => "ui-btn-right", :data => {icon:"delete"})
%div
  = render 'form'
  

schoolmate/app/views/years/new.html.haml
= content_for :title do
  Новый учебный год
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => study_path}
    Учеба  
%div
  = render 'form'