schoolmate/config/routes.rb
Schoolmate::Application.routes.draw do
  root :to => 'diary#index'

  resources :users
  resources :sessions
  resources :notifications
  resources :profiles
  resources :finances
  resources :options do
    collection do
      get  :index
      get  :about
      get  :feedback
      post :send_feedback
    end
  end
  resources :years do
    resources :terms do
      member do 
        get 'assign_subject'
        post 'add_subject'
      end
    end
  end
  resources :exams
  resources :exam_watchers
  resources :subjects
  resources :marks

  match "login"     => "sessions#new", :via => :get
  match "logout"    => "sessions#destroy", :via => :get
  match "signup"    => "users#new", :via => :get
  match 'diary'     => 'diary#index'
  match 'diary_add' => 'diary#add'
  match 'home'      => 'home#index', :via => :get
  match 'study'     => 'study#index', :via => :get
  



  

end

schoolmate/app/models/term.rb
class Term < ActiveRecord::Base

    belongs_to :user
    belongs_to :year
    has_and_belongs_to_many :subjects

    attr_accessible :year_id, :user_id, :name, :start_date, :finish_date
    validates :name, :presence => true
    validates :start_date, :presence => true
    validates :finish_date, :presence => true

    def assign_subjects(subjects_arr)
        self.subjects.clear
        arr = subjects_arr.keys.map{|k| k.to_i } 
        self.subjects << Subject.find(arr)
        save
    end

end

schoolmate/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation
    has_secure_password
	validates_presence_of :password, :on => :create

	belongs_to :profile
    has_many   :notifications
    has_many   :feedbacks
    has_many   :finances
    has_many   :subjects
    has_many   :years
    has_many   :terms

end

schoolmate/app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_filter :require_authentication
  layout "mobile"
  
  def edit
    @term = Term.find(params[:id])
    @year = Year.find(params[:year_id])
  end

  def destroy
    term = Term.find(params[:id])
    if term.user_id != current_user.id
        flash[:error] = t('term.not_belong')
        redirect_to study_path
    end
    if term.delete
        flash[:info] = t('term.deleted')
    else
        flash[:error] = t('term.delete_error')
    end
    redirect_to study_path 
  end

  def create
    term = Term.new(
      name:params[:name], user_id:current_user.id, 
      year_id:params[:year_id],
      start_date:params[:start_date],
      finish_date:params[:finish_date]
      )
    year = Year.find(params[:year_id])
    if term.save
      flash[:info] = t('term.created')
      redirect_to study_path  
    else
      flash[:error] = t('term.create_error')
      redirect_to new_year_term_path(year)
    end    
  end

  def new
    @year = Year.find(params[:year_id])
    @term = Term.new
  end

  def update
    term = Term.find(params[:id])    
    if term.user_id != current_user.id
        flash[:error] = t('term.not_belong')
        redirect_to study_path
    end
    term.name = params[:name]
    term.start_date = params[:start_date]
    term.finish_date = params[:finish_date]
    if term.save
        flash[:info] = t('term.updated')
    else
        flash[:error] = t('term.update_error')
    end    
    redirect_to study_path 
  end

  def assign_subject
    @term = Term.find(params[:id])
    @year = Year.find(params[:year_id])
    @subjects = current_user.subjects.includes(:terms => :subjects)
    #raise current_user.subjects.includes(:terms => :subjects).explain
    #@term_subjects = @term.subjects
  end

  def add_subject
    term = Term.find(params[:id])
    year = Year.find(params[:year_id])
    if term.assign_subjects(params[:subjects])
      flash[:info] = t('term.subjects_assigned')
      redirect_to study_path
    else
      flash[:error] = t('term.subjects_assign_error')
      redirect_to assign_subject_year_term_path(year, term)
    end
    
  end

end

schoolmate/app/views/terms/_form.html.haml
= form_for [@year, @term] do |f|
  %div
    = label_tag(:name, "Название:")
    = text_field_tag(:name, @term.name, :placeholder => "название" )
    = label_tag(:start_date, "Дата начала:")
    = text_field_tag(:start_date, proper_date(@term.start_date), :placeholder => Time.now.strftime("%d-%m-%Y") )
    -#%input#date{:name => "start_date", :type => "date", :value => @term.start_date}/
    = label_tag(:finish_date, "Дата окончания:")
    = text_field_tag(:finish_date, proper_date(@term.finish_date), :placeholder => finish_date_for_term )
    -#%input#date{:name => "finish_date", :type => "date", :value => @term.finish_date}/
    = f.submit "Сохранить" 

schoolmate/app/views/terms/assign_subject.html.haml
= content_for :title do
  Предметы в четверти
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => study_path}
    Учеба  
%div
  = form_tag(add_subject_year_term_path(@year, @term), :method => :post) do
    %div{"data-role" => "fieldcontain"}
      %fieldset{"data-role" => "controlgroup"}
        - @subjects.each do |s|
          = check_box_tag("subjects[#{s.id}]", 1, s.term_ids.include?(@term.id), { class:"custom" })
          = label_tag "subjects[#{s.id}]", s.name
    = submit_tag "Сохранить"

schoolmate/app/views/terms/edit.html.haml
= content_for :title do
  = @term.name
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => study_path}
    Учеба  
  = link_to("Удалить", year_term_path(@year, @term), :method => :delete, :class => "ui-btn-right", :data => {icon:"delete"})
%div
  = render 'form'
  

schoolmate/app/views/terms/new.html.haml
= content_for :title do
  Новая четверть
= content_for :buttons do
  %a{"data-icon" => "arrow-l", :href => study_path}
    Учеба  
%div
  = render 'form'